
package library_management_system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;



/**
 *
 * @author eru
 */
public class add_membership extends javax.swing.JFrame implements InputValidation {
    
    @Override
    public boolean validateFields() {
        return !newId.getText().isEmpty()
            && !newName.getText().isEmpty()
            && !newPhone.getText().isEmpty()
            && !newDate.getText().isEmpty();
    }

    @Override
    public void showMessage(String message) {
         JOptionPane.showMessageDialog(this, message);
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(add_membership.class.getName());

    /**
     * Creates new form add_membership
     */
    public add_membership() {
        initComponents();
    }
    
    private void addMembership(Member member) throws dbErrorException {

    String sql = "INSERT INTO memberships (mem_id, mem_name, mem_phone, mem_registered) "
               + "VALUES (?, ?, ?, ?)";

    try (Connection conn = DBConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql)) {

        ps.setString(1, member.getId());
        ps.setString(2, member.getName());
        ps.setString(3, member.getPhone());

       
        LocalDate parsedDate = LocalDate.parse(
            member.getRegisteredDate(),
            DateTimeFormatter.ofPattern("yyyy-MM-dd")
        );

        ps.setDate(4, java.sql.Date.valueOf(parsedDate));

        ps.executeUpdate();

    } catch (SQLException | DateTimeParseException e) {
        e.printStackTrace(); 
        throw new dbErrorException("Failed to add membership");
    }
}

    
    private void clearFields() {
        newId.setText("");
        newName.setText("");
        newPhone.setText("");
        newDate.setText("");
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        newName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        newPhone = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();
        create = new javax.swing.JButton();
        newDate = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        newId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 450));
        setMinimumSize(new java.awt.Dimension(700, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("FreeSans", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NEW MEMBERSHIP");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        newName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newNameActionPerformed(evt);
            }
        });
        getContentPane().add(newName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 290, 20));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 134, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, 20));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, 20));

        newPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPhoneActionPerformed(evt);
            }
        });
        getContentPane().add(newPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 290, -1));

        cancel.setBackground(new java.awt.Color(204, 204, 204));
        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/pics/Untitled design (2).png"))); // NOI18N
        cancel.setText("CANCEL");
        cancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 91, 41));

        create.setBackground(new java.awt.Color(204, 204, 204));
        create.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/pics/Untitled design (1).png"))); // NOI18N
        create.setText("CREATE");
        create.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        getContentPane().add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 91, 41));

        newDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDateActionPerformed(evt);
            }
        });
        getContentPane().add(newDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 290, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/pics/logo.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ID:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));
        getContentPane().add(newId, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 290, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/pics/bg.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newNameActionPerformed

    private void newPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPhoneActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        // TODO add your handling code here:
        try {

       
        if (!validateFields()) {
            showMessage("Please fill all fields");
            return;
        }    
            Member member = new Member();

            member.setId(newId.getText());
            member.setName(newName.getText());
            member.setPhone(newPhone.getText());
            member.setRegisteredDate(newDate.getText());

            addMembership(member);

        JOptionPane.showMessageDialog(
            this,
            "Membership added successfully!",
            "Success",
            JOptionPane.INFORMATION_MESSAGE
        );

        clearFields();

    } catch (dbErrorException e) {
        // Show database error
        JOptionPane.showMessageDialog(
            this,
            e.getMessage(),
            "Database Error",
            JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_createActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(() -> {
                Dashboard dashboard = new Dashboard();
                dashboard.setLocationRelativeTo(null);
                dashboard.setVisible(true);
            });
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void newDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newDateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new add_membership().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JButton create;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JFormattedTextField newDate;
    private javax.swing.JTextField newId;
    private javax.swing.JTextField newName;
    private javax.swing.JTextField newPhone;
    // End of variables declaration//GEN-END:variables

}
