package library_management_system;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */


public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel7 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        panel3 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        canvas1 = new java.awt.Canvas();
        member_create = new javax.swing.JButton();
        member_edit = new javax.swing.JButton();
        book_view = new javax.swing.JButton();
        book_add = new javax.swing.JButton();
        member_view = new javax.swing.JButton();
        book_remove = new javax.swing.JButton();
        new_rent = new javax.swing.JButton();
        view_rent = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        ReturnRent = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(325, 125));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(700, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 462, -1, -1));

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 219, Short.MAX_VALUE)
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 462, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/pics/logo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 140, 100));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 42)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DASHBOARD");
        jLabel3.setAlignmentY(0.0F);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 270, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("BOOK");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 80, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("RENTING");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 120, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MEMBERSHIP");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, 40));
        getContentPane().add(canvas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, -1, -1));

        member_create.setBackground(new java.awt.Color(204, 204, 204));
        member_create.setText("CREATE");
        member_create.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        member_create.addActionListener(this::member_createActionPerformed);
        getContentPane().add(member_create, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 220, 60));

        member_edit.setBackground(new java.awt.Color(204, 204, 204));
        member_edit.setText("EDIT");
        member_edit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        member_edit.addActionListener(this::member_editActionPerformed);
        getContentPane().add(member_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 220, 60));

        book_view.setBackground(new java.awt.Color(204, 204, 204));
        book_view.setText("VIEW");
        book_view.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        book_view.addActionListener(this::book_viewActionPerformed);
        getContentPane().add(book_view, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 220, 60));

        book_add.setBackground(new java.awt.Color(204, 204, 204));
        book_add.setText("ADD");
        book_add.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        book_add.addActionListener(this::book_addActionPerformed);
        getContentPane().add(book_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 260, 60));

        member_view.setBackground(new java.awt.Color(204, 204, 204));
        member_view.setText("VIEW");
        member_view.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        member_view.addActionListener(this::member_viewActionPerformed);
        getContentPane().add(member_view, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 260, 60));

        book_remove.setBackground(new java.awt.Color(204, 204, 204));
        book_remove.setText("REMOVE");
        book_remove.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        book_remove.addActionListener(this::book_removeActionPerformed);
        getContentPane().add(book_remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 220, 60));

        new_rent.setBackground(new java.awt.Color(204, 204, 204));
        new_rent.setText("NEW");
        new_rent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        new_rent.addActionListener(this::new_rentActionPerformed);
        getContentPane().add(new_rent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 220, 60));

        view_rent.setBackground(new java.awt.Color(204, 204, 204));
        view_rent.setText("VIEW");
        view_rent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        view_rent.addActionListener(this::view_rentActionPerformed);
        getContentPane().add(view_rent, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 220, 60));

        logout.setBackground(new java.awt.Color(204, 204, 204));
        logout.setText("  Log Out  ");
        logout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logout.addActionListener(this::logoutActionPerformed);
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        ReturnRent.setBackground(new java.awt.Color(204, 204, 204));
        ReturnRent.setText("RETURN");
        ReturnRent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ReturnRent.addActionListener(this::ReturnRentActionPerformed);
        getContentPane().add(ReturnRent, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 260, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/pics/bg.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void book_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_addActionPerformed
         //new AddBook().setVisible(true);
         java.awt.EventQueue.invokeLater(() -> {
        add_book addbook = new add_book();
        addbook.setLocationRelativeTo(null);
        addbook.setVisible(true);
        });  
    this.dispose();
    }//GEN-LAST:event_book_addActionPerformed

    private void new_rentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_rentActionPerformed
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(() -> {
            RentingForm rentform = new RentingForm();
            rentform.setLocationRelativeTo(null);
            rentform.setVisible(true);
        });
        this.dispose();
    }//GEN-LAST:event_new_rentActionPerformed

    private void book_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_removeActionPerformed
         //new RemoveBook().setVisible(true);
         java.awt.EventQueue.invokeLater(() -> {
        Remove_Book removebook = new Remove_Book();
        removebook.setLocationRelativeTo(null);
        removebook.setVisible(true);
        });  
    this.dispose();
    }//GEN-LAST:event_book_removeActionPerformed

    private void view_rentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_rentActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(() -> {
            rental_list rentlist = new rental_list();
            rentlist.setLocationRelativeTo(null);
            rentlist.setVisible(true);
        });
        this.dispose();
    }//GEN-LAST:event_view_rentActionPerformed

    private void member_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_member_createActionPerformed
         //new CreateMember().setVisible(true);
         java.awt.EventQueue.invokeLater(() -> {
                add_membership addmem = new add_membership();
                addmem.setLocationRelativeTo(null);
                addmem.setVisible(true);
            });
    this.dispose();
    }//GEN-LAST:event_member_createActionPerformed

    private void member_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_member_viewActionPerformed
        //new ViewMember().setVisible(true);
        java.awt.EventQueue.invokeLater(() -> {
                view_memberships viewmem = new view_memberships();
                viewmem.setLocationRelativeTo(null);
                viewmem.setVisible(true);
            });
    this.dispose();
    }//GEN-LAST:event_member_viewActionPerformed

    private void member_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_member_editActionPerformed
        //new EditMember().setVisible(true);
        java.awt.EventQueue.invokeLater(() -> {
        edit_membership editmem = new edit_membership();
        editmem.setLocationRelativeTo(null);
        editmem.setVisible(true);
        });  
        this.dispose();
    this.dispose();
    }//GEN-LAST:event_member_editActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
        login loginForm = new login();
        loginForm.setLocationRelativeTo(null);
        loginForm.setVisible(true);
        });  
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void book_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_viewActionPerformed
        //new ViewBook().setVisible(true);
        java.awt.EventQueue.invokeLater(() -> {
            ViewBook viewbook = new ViewBook();
            viewbook.setLocationRelativeTo(null);
            viewbook.setVisible(true);
        });
        this.dispose();
    }//GEN-LAST:event_book_viewActionPerformed

    private void ReturnRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnRentActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(() -> {
            ReturnForm returnrent = new ReturnForm();
            returnrent.setLocationRelativeTo(null);
            returnrent.setVisible(true);
        });
        this.dispose();
    }//GEN-LAST:event_ReturnRentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReturnRent;
    private javax.swing.JButton book_add;
    private javax.swing.JButton book_remove;
    private javax.swing.JButton book_view;
    private java.awt.Canvas canvas1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton logout;
    private javax.swing.JButton member_create;
    private javax.swing.JButton member_edit;
    private javax.swing.JButton member_view;
    private javax.swing.JButton new_rent;
    private java.awt.Panel panel1;
    private java.awt.Panel panel3;
    private javax.swing.JButton view_rent;
    // End of variables declaration//GEN-END:variables
}
