/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library_management_system;

import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author nrnjm
 */
public class edit_membership extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(edit_membership.class.getName());

    /**
     * Creates new form edit_membership
     */
    public edit_membership() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fullname = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        status = new javax.swing.JComboBox<>();
        searchButton = new javax.swing.JButton();
        save = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(325, 125));
        setMaximumSize(new java.awt.Dimension(700, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 190, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/pics/logo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 140, 110));
        getContentPane().add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 290, -1));
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 290, -1));

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Unactive", "Revoked" }));
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 290, -1));

        searchButton.setBackground(new java.awt.Color(204, 204, 204));
        searchButton.setText("Find");
        searchButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchButton.addActionListener(this::searchButtonActionPerformed);
        getContentPane().add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 80, -1));

        save.setBackground(new java.awt.Color(204, 204, 204));
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/pics/Untitled design (1).png"))); // NOI18N
        save.setText("SAVE");
        save.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        save.addActionListener(this::saveActionPerformed);
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 100, 50));

        cancel.setBackground(new java.awt.Color(204, 204, 204));
        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/pics/Untitled design (2).png"))); // NOI18N
        cancel.setText("CANCEL");
        cancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancel.addActionListener(this::cancelActionPerformed);
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 100, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EDIT MEMBERSHIP ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Status:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Full name:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Phone No:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/pics/bg.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(() -> {
                Dashboard dashboard = new Dashboard();
                dashboard.setLocationRelativeTo(null);
                dashboard.setVisible(true);
            });
            
            this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        String ID;
        int notFound = 0;
        try {
 
            Connection con = DBConnection.getConnection();
            Statement st = con.createStatement();
            
            ID = search.getText();
            if(ID.isEmpty()){
              JOptionPane.showMessageDialog(this, "ID is require", "Dialog",
                                     JOptionPane.ERROR_MESSAGE);
            }else {
               String sql = "SELECT * FROM memberships WHERE mem_id='"+ID+"'";
               ResultSet rs = st.executeQuery(sql);
               while(rs.next()){
                   fullname.setText(rs.getString("mem_name"));
                   phone.setText(rs.getString("mem_phone"));
                   notFound = 1;

               }
               if(notFound == 0){
                  JOptionPane.showMessageDialog(new JFrame(), "invalid ID", "Dialog",
                                     JOptionPane.ERROR_MESSAGE);
               }
            }
        }catch(Exception e){
            System.out.println("Error "+ e.getMessage());
            
        }    
    }//GEN-LAST:event_searchButtonActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        String ID = search.getText();
    int notFound = 1;
    String name, no, stat;

    try {
        Connection conn = DBConnection.getConnection();

        Statement selectSt = conn.createStatement();
        Statement updateSt = conn.createStatement();

        if (ID.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "ID is required",
                    "Dialog",
                    JOptionPane.ERROR_MESSAGE
            );
        } else {
            String sql = "SELECT * FROM memberships WHERE mem_id='" + ID + "'";
            ResultSet rs = selectSt.executeQuery(sql);

            if (rs.next()) {
                notFound = 0;

                name = fullname.getText();
                no = phone.getText();
                stat = status.getSelectedItem().toString();

                String sql2 =
                        "UPDATE memberships SET mem_name='" + name +
                        "', mem_phone='" + no +
                        "', mem_status='" + stat +
                        "' WHERE mem_id='" + ID + "'";

                updateSt.executeUpdate(sql2);

                JOptionPane.showMessageDialog(this, "Member updated successfully");
            }

            if (notFound == 1) {
                JOptionPane.showMessageDialog(
                        this,
                        "Invalid ID",
                        "Dialog",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        }

    } catch (Exception e) {
        System.out.println("Error " + e.getMessage());
    }
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new edit_membership().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JTextField fullname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField phone;
    private javax.swing.JButton save;
    private javax.swing.JTextField search;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox<String> status;
    // End of variables declaration//GEN-END:variables
}
