/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library_management_system;

import java.sql.*;
import java.time.LocalDate;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import java.util.logging.Logger;

/**
 *
 * @author user
 */
public class RentingForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RentingForm.class.getName());

    /**
     * Creates new form RentingForm
     */
    public RentingForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rentDurationTxt = new javax.swing.JTextField();
        rentMemberidTxt = new javax.swing.JTextField();
        rentBookidTxt = new javax.swing.JTextField();
        rentDonebtn = new javax.swing.JButton();
        rentCancelbtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Renting Form");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Book ID:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 158, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Member ID:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 211, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Duration Days:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 264, -1, -1));

        rentDurationTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(rentDurationTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 259, 292, 35));

        rentMemberidTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(rentMemberidTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 206, 292, 35));

        rentBookidTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(rentBookidTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 153, 292, 35));

        rentDonebtn.setBackground(new java.awt.Color(204, 204, 204));
        rentDonebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rentDonebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/pics/done.png"))); // NOI18N
        rentDonebtn.setText("Done");
        rentDonebtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rentDonebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentDonebtnActionPerformed(evt);
            }
        });
        getContentPane().add(rentDonebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 322, 100, -1));

        rentCancelbtn.setBackground(new java.awt.Color(204, 204, 204));
        rentCancelbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rentCancelbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/pics/cancel.png"))); // NOI18N
        rentCancelbtn.setText("Cancel");
        rentCancelbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rentCancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentCancelbtnActionPerformed(evt);
            }
        });
        getContentPane().add(rentCancelbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 322, 110, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/pics/logo.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/pics/bg.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rentDonebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentDonebtnActionPerformed
    
    String bookId = rentBookidTxt.getText().trim();
    String memberId = rentMemberidTxt.getText().trim();
    String duration = rentDurationTxt.getText().trim();

    if (bookId.isEmpty() || memberId.isEmpty() || duration.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill all fields.");
        return;
    }

    int days;
    try {
        days = Integer.parseInt(duration);
        if (days <= 0) {
            JOptionPane.showMessageDialog(this, "Duration must be more than 0.");
            return;
        }
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Duration must be an integer.");
        return;
    }

    String checkBookStatus = "SELECT book_status FROM books WHERE book_id = ?";
    String insertRental = "INSERT INTO rentals (book_id, mem_id, days) VALUES (?, ?, ?)";
    String updateBook = "UPDATE books SET book_status = 'Rented' WHERE book_id = ?";

    try (Connection conn = DriverManager.getConnection("jdbc:mysql://100.75.93.2:3306/library_management_system", "najmi", "Katakunci#25");
         PreparedStatement checkStmt = conn.prepareStatement(checkBookStatus);
         PreparedStatement pstmt1 = conn.prepareStatement(insertRental);
         PreparedStatement pstmt2 = conn.prepareStatement(updateBook)) {

        checkStmt.setString(1, bookId);
        try (ResultSet rs = checkStmt.executeQuery()) {
            if (!rs.next()) {
                JOptionPane.showMessageDialog(this, "Book not found.");
                return;
            }
            String status = rs.getString("book_status");
            if (!"Available".equals(status)) {
                JOptionPane.showMessageDialog(this, "Book is already rented.");
                return;
            }
        }

        pstmt1.setString(1, bookId);
        pstmt1.setString(2, memberId);
        pstmt1.setInt(3, days);
        pstmt2.setString(1, bookId);

        pstmt2.executeUpdate();
        int rowsInserted = pstmt1.executeUpdate();
        System.out.println("Rows inserted: " + rowsInserted);

        JOptionPane.showMessageDialog(this, "Book rented successfully!");
        rentBookidTxt.setText("");
        rentMemberidTxt.setText("");
        rentDurationTxt.setText("");
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error renting book.");
    }
    
    }//GEN-LAST:event_rentDonebtnActionPerformed

    private void rentCancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentCancelbtnActionPerformed
    java.awt.EventQueue.invokeLater(() -> {
                Dashboard dashboard = new Dashboard();
                dashboard.setLocationRelativeTo(null);
                dashboard.setVisible(true);
            });
            
            this.dispose();
    }//GEN-LAST:event_rentCancelbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RentingForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField rentBookidTxt;
    private javax.swing.JButton rentCancelbtn;
    private javax.swing.JButton rentDonebtn;
    private javax.swing.JTextField rentDurationTxt;
    private javax.swing.JTextField rentMemberidTxt;
    // End of variables declaration//GEN-END:variables

    private String saveRental(String bookId, String memberId, String duration) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
