/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library_management_system;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class ReturnForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReturnForm.class.getName());

    /**
     * Creates new form ReturnForm
     */
    public ReturnForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        returnMemberidTxt = new javax.swing.JTextField();
        returnBookidTxt = new javax.swing.JTextField();
        returnDonebtn = new javax.swing.JButton();
        returnCancelbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Return Form");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 47, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Book ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 169, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Member ID:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 222, -1, -1));

        returnMemberidTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(returnMemberidTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 217, 264, 35));

        returnBookidTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(returnBookidTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 164, 264, 35));

        returnDonebtn.setBackground(new java.awt.Color(204, 204, 204));
        returnDonebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        returnDonebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/pics/done.png"))); // NOI18N
        returnDonebtn.setText("Done");
        returnDonebtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        returnDonebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnDonebtnActionPerformed(evt);
            }
        });
        getContentPane().add(returnDonebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 300, 110, -1));

        returnCancelbtn.setBackground(new java.awt.Color(204, 204, 204));
        returnCancelbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        returnCancelbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/pics/cancel.png"))); // NOI18N
        returnCancelbtn.setText("Cancel");
        returnCancelbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        returnCancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnCancelbtnActionPerformed(evt);
            }
        });
        getContentPane().add(returnCancelbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 300, 110, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/pics/logo.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/pics/bg.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnDonebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnDonebtnActionPerformed
                                                 
    String bookId = returnBookidTxt.getText().trim();
    String memberId = returnMemberidTxt.getText().trim();

    if (bookId.isEmpty() || memberId.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter both Book ID and Member ID.");
        return;
    }

    String checkRental = "SELECT book_status FROM books WHERE book_id = ?";
    String deleteRental = "DELETE FROM rentals WHERE book_id = ? AND mem_id = ?";
    String updateBook = "UPDATE books SET book_status = 'Available' WHERE book_id = ?";

    try (Connection conn = DriverManager.getConnection("jdbc:mysql://100.75.93.2:3306/library_management_system", "najmi", "Katakunci#25");
         PreparedStatement checkStmt = conn.prepareStatement(checkRental);
         PreparedStatement pstmt1 = conn.prepareStatement(deleteRental);
         PreparedStatement pstmt2 = conn.prepareStatement(updateBook)) {

        checkStmt.setString(1, bookId);
        try (ResultSet rs = checkStmt.executeQuery()) {
            if (!rs.next()) {
                JOptionPane.showMessageDialog(this, "Book not found.");
                return;
            }
            String status = rs.getString("book_status");
            if ("Available".equals(status)) {
                JOptionPane.showMessageDialog(this, "Book is already available.");
                return;
            }
        }

        pstmt1.setString(1, bookId);
        pstmt1.setString(2, memberId);
        int rowsDeleted = pstmt1.executeUpdate();

        if (rowsDeleted > 0) {
            pstmt2.setString(1, bookId);
            pstmt2.executeUpdate();
            JOptionPane.showMessageDialog(this, "Book returned successfully!");
            returnBookidTxt.setText("");
            returnMemberidTxt.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Rental record not found for Book ID: " + bookId + " and Member ID: " + memberId);
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error returning book.");
    }

    }//GEN-LAST:event_returnDonebtnActionPerformed

    private void returnCancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnCancelbtnActionPerformed
      java.awt.EventQueue.invokeLater(() -> {
                Dashboard dashboard = new Dashboard();
                dashboard.setLocationRelativeTo(null);
                dashboard.setVisible(true);
            });
            
            this.dispose();
    }//GEN-LAST:event_returnCancelbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReturnForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField returnBookidTxt;
    private javax.swing.JButton returnCancelbtn;
    private javax.swing.JButton returnDonebtn;
    private javax.swing.JTextField returnMemberidTxt;
    // End of variables declaration//GEN-END:variables
}
